/*
 * Power brModelo - Kotlin port of brModelo 3.0 originally written in Pascal
 * Copyright (C) 2026  Polyana Fontes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// Generates a BuildInfo.kt file in commonMain so the running application can
// display the Gradle project version together with the CI build metadata
// (GITHUB_RUN_NUMBER and the short commit SHA from GITHUB_SHA) when present.
val generatedBuildInfoDir = layout.buildDirectory.dir("generated/source/buildInfo/commonMain/kotlin")

val generateBuildInfo = tasks.register("generateBuildInfo") {
    val projectVersion = providers.provider { project.version.toString() }
    val runNumber = providers.environmentVariable("GITHUB_RUN_NUMBER").orElse("")
    val commitSha = providers.environmentVariable("GITHUB_SHA").orElse("")

    inputs.property("version", projectVersion)
    inputs.property("runNumber", runNumber)
    inputs.property("commitSha", commitSha)
    outputs.dir(generatedBuildInfoDir)

    doLast {
        val pkgDir = generatedBuildInfoDir.get().asFile.resolve("games/polyclub/power/brmodelo")
        pkgDir.mkdirs()
        val shortSha = commitSha.get().take(7)
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            // Generated by the :composeApp:generateBuildInfo Gradle task. Do not edit by hand.
            package games.polyclub.power.brmodelo

            internal object BuildInfo {
                const val VERSION: String = "${projectVersion.get()}"
                const val GITHUB_RUN_NUMBER: String = "${runNumber.get()}"
                const val GIT_COMMIT_SHORT: String = "$shortSha"

                /**
                 * Human-readable version string suitable for window titles.
                 *
                 * Returns just [VERSION] for local builds, or appends
                 * `(build #<run> <sha>)` when running under GitHub Actions.
                 */
                val displayVersion: String
                    get() = when {
                        GITHUB_RUN_NUMBER.isNotEmpty() && GIT_COMMIT_SHORT.isNotEmpty() ->
                            "${'$'}VERSION (build #${'$'}GITHUB_RUN_NUMBER ${'$'}GIT_COMMIT_SHORT)"
                        GITHUB_RUN_NUMBER.isNotEmpty() ->
                            "${'$'}VERSION (build #${'$'}GITHUB_RUN_NUMBER)"
                        GIT_COMMIT_SHORT.isNotEmpty() ->
                            "${'$'}VERSION (${'$'}GIT_COMMIT_SHORT)"
                        else -> VERSION
                    }
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvm("desktop")

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "composeApp"
        browser()
        binaries.executable()
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
            }
        }

        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.flatlaf)
            }
        }

        val wasmJsMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(libs.kotlin.test)
            }
        }
    }
}

compose.resources {
    packageOfResClass = "games.polyclub.power.brmodelo.generated.resources"
}

compose.desktop {
    application {
        mainClass = "games.polyclub.power.brmodelo.MainKt"
    }
}
