/*
 * Power brModelo - Kotlin port of brModelo 3.0 originally written in Pascal
 * Copyright (C) 2026  Polyana Fontes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package games.polyclub.power.brmodelo.mcp

/**
 * MCP `server.instructions` text (English). Cursor and other clients expose this
 * to the model — keep the canonical URI index here instead of duplicating it
 * across individual tool descriptions.
 */
internal object McpServerInstructions {

    /**
     * Appended to tools that load or author MER XML so agents look at the
     * instruction block instead of guessing paths on disk.
     */
    const val MER_XML_REFERENCE_SEE_INSTRUCTIONS: String =
        "Authoritative MCP resource URIs (DTD, frozen example MER files, live tab XML, live tab PNG/JPEG previews) are listed in this server's MCP instructions from resources/list — use those URIs; do not search the host filesystem for sample XML."

    fun build(): String = buildString {
        append("This MCP server controls the Power-brModelo desktop editor. ")
        append("Tab tool names use the prefix \"tabs")
        append(McpTabToolNames.TAB_TOOL_SEPARATOR)
        append("\" (category + suffix). ")
        append("Procedural canvas placement tools use the prefix \"tools")
        append(McpProceduralToolsToolNames.TOOLS_SEPARATOR)
        append("\". ")
        append("Property edits aligned with the sidebar inspector use the prefix \"")
        append(McpEditToolNames.EDIT_GROUP)
        append(McpEditToolNames.EDIT_SEPARATOR)
        append("\" (e.g. ")
        append(McpEditToolNames.MODEL)
        append(", ")
        append(McpEditToolNames.CANVAS_ELEMENT)
        append(", ")
        append(McpEditToolNames.CONNECTION)
        append(", ")
        append(McpEditToolNames.HIDDEN_ATTRIBUTE)
        append(", ")
        append(McpEditToolNames.CANVAS_SELECTION)
        append(", ")
        append(McpEditToolNames.CANVAS_SELECTION_RECTANGLE)
        append("). ")
        append("Conceptual search tools use the prefix \"")
        append(McpSearchToolNames.SEARCH_GROUP)
        append(McpSearchToolNames.SEARCH_SEPARATOR)
        append("\" (same behaviour as the editor **Localizar** UI). ")
        append("Raster export helpers use the prefix \"")
        append(McpExportToolNames.EXPORT_GROUP)
        append(McpExportToolNames.EXPORT_SEPARATOR)
        append("\". ")
        append("Operation-menu commands use the prefix \"")
        append(McpOperationToolNames.OPERATION_GROUP)
        append(McpOperationToolNames.OPERATION_SEPARATOR)
        append("\". ")
        append("Use only letters, digits, and underscores in tool names where the client is strict.\n\n")

        append("## Agent pitfalls (MER layout & conceptual links)\n\n")
        append("English quick-reference for automation:\n")
        append("- Leave roughly **24–32 px** of clear edge-to-edge space between new entity boxes before calling ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append(" (full editor link tool) so auto-created diamonds and cardinalities do not stack on neighbours; ")
        append(McpProceduralToolsToolNames.LINK_EXISTING_ENDPOINTS)
        append(" does not create a plain entity–entity midpoint diamond, but still benefits from the same spacing once legs exist.\n")
        append("- After a burst of placement calls, run ")
        append(McpTabToolNames.LIST_OPEN)
        append(" if needed, then ")
        append(McpOperationToolNames.LAYOUT_QUALITY)
        append(" (or rely on merged `layoutQuality` on procedural successes). Treat `layoutQuality.hasBlockingOverlap`, ")
        append("`affectedElementIds`, and `agentHint` as **heuristics**; use tab `.png`/`.jpg` or subset raster export when you need pixel truth.\n")
        append("- Linking a **plain entity** to the **outer rectangle** of an associative entity with ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append(" matches editor clicks: the domain may introduce another relationship diamond with an **auto-generated** name — this is **not** ")
        append("a rename of the inner associative label (`relationshipName` / \"realiza\"). Inspect `linkPattern` on ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append(" success JSON (`entity_associative_outer_bridge`, etc.). For the usual \"connect this entity to the associative **relationship**\" intent without that bridge, prefer ")
        append(McpProceduralToolsToolNames.LINK_EXISTING_ENDPOINTS)
        append(" (it rewrites entity+outer to entity+inner when applicable) or pass `\"associativeOuterEntitySide\": false` explicitly on ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append(".\n")
        append("- Associative **inner** diamond / \"miolo\" links (entity ↔ inner relationship of an associative entity, same as a human click on the inner diamond): ")
        append("use `endA`/`endB` picks where the associative side sets `\"associativeOuterEntitySide\": false` for that `elementId` (outer rectangle uses `true`). ")
        append("Example JSON fragment: `{\"elementId\": 42, \"associativeOuterEntitySide\": false}`.\n")
        append("- Frozen reference diagram with many construct kinds (including associative entities): `brmodelo://example/mer_multi_component_palette` ")
        append("(also listed under **Frozen example MER XML** below).\n\n")

        append("## Lightweight diagram discovery\n\n")
        append("Prefer targeted tools before dumping a whole tab via `resources/read` on `.xml`: `")
        append(McpSearchToolNames.FIND)
        append("` (same behaviour as **Localizar**), `")
        append(McpEditToolNames.CANVAS_SELECTION_RECTANGLE)
        append("` with `dryRun` true to preview `objectsInBand` / selection deltas without mutating the canvas, ")
        append("and tab `.png`/`.jpg` resources, `")
        append(McpExportToolNames.CANVAS_ELEMENTS_DETAIL)
        append("` for structured element JSON by id (optional Ctrl+C-style raster), or `")
        append(McpExportToolNames.SUBSET_RASTER)
        append("` for pixel-accurate routing. ")
        append("Reserve full MER XML reads for deterministic bulk edits (`")
        append(McpTabToolNames.PATCH_MODEL_XML)
        append("`, `")
        append(McpTabToolNames.REPLACE_MODEL_XML)
        append("`) rather than exploratory browsing.\n\n")

        append("## MCP resources (resources/list + resources/read)\n\n")

        append("### Live editor tabs\n")
        append("Per open conceptual tab the server registers three resources keyed by the stable session id from ")
        append(McpTabToolNames.LIST_OPEN)
        append(" (field `id`), not the list index, so URIs stay valid when other tabs are closed:\n")
        append("- `brmodelo://model/{editorTabSessionId}.xml` — current in-memory MER XML (text; same as a saved export).\n")
        append("- `brmodelo://model/{editorTabSessionId}.png` — raster preview, same as **Exportar em PNG** (transparent background, tight crop); read via `resources/read` as base64 blob.\n")
        append("- `brmodelo://model/{editorTabSessionId}.jpg` — raster preview, same as **Exportar em JPEG** (opaque canvas-gray background, tight crop); read via `resources/read` as base64 blob.\n")
        append("Tab tools that identify a tab by `resourceUri` (select, close, save, and all other tab-scoped tools) accept **any** of these three suffixes for the same tab; static example/DTD URIs are not valid there.\n")
        append("The `")
        append(McpTabToolNames.LIST_OPEN)
        append("` JSON includes `selectedTabIndex`, `selectedTabSessionId`, and each row has `tabIndex` plus `isSelected` so agents know which tab the user is editing.\n")
        append("**Legacy pitfall:** `brmodelo://model/{n}` **without** a `.xml`/`.png`/`.jpg` suffix is treated as a **tab list index** (0-based), not a session id — after ")
        append(McpTabToolNames.NEW_CONCEPTUAL_MODEL)
        append(" appends a tab, index `0` still points at the **first** diagram. Always pass the numeric `id` from ")
        append(McpTabToolNames.LIST_OPEN)
        append(" with a surface suffix (e.g. `.xml`).\n")
        append("The resource-utility tools that return **plain text** only support the tab `.xml` URI (and DTD/examples); for `.png`/`.jpg` use `resources/read`.\n")
        append("**Suggestion for vision-capable agents:** after substantive diagram or layout changes, occasionally call `resources/read` on the tab `.png` or `.jpg` URI (from ")
        append(McpTabToolNames.LIST_OPEN)
        append(") and visually inspect the preview to confirm the model looks clear and pleasant, and that elements, connectors, and labels are not unnecessarily stacked or overlapping. ")
        append("Opaque **JPEG** tab previews tend to be easier for vision models than **PNG** (transparent background may appear as solid black in some pipelines).\n")
        append("For a **partial** diagram preview (chosen element ids, same crop style as Ctrl+C clipboard image), call ")
        append(McpExportToolNames.SUBSET_RASTER)
        append(" with format `png` (transparent) or `jpg`/`jpeg` (opaque canvas-gray). ")
        append("To read the **user's current selection** as JSON (and optionally the same subgraph as a raster), call ")
        append(McpExportToolNames.CURRENT_CANVAS_SELECTION)
        append(" — omit `imageFormat` for data-only, or pass `imageFormat` `png`/`jpg`/`jpeg` when the agent can consume images.\n")
        append("Successful calls to ")
        append(McpTabToolNames.NEW_CONCEPTUAL_MODEL)
        append(", ")
        append(McpTabToolNames.OPEN_XML)
        append(", and ")
        append(McpTabToolNames.OPEN_FILE)
        append(" return JSON with createdResourceUri, selectedResourceUri, ")
        append("plus createdResourceUriPng, createdResourceUriJpeg, selectedResourceUriPng, and selectedResourceUriJpeg ")
        append("(PNG/JPEG URIs match the menu export; created identifies the tab that received the new model; ")
        append("numeric `createdSessionId` and `selectedSessionId` mirror those stable ids; ")
        append("for ")
        append(McpTabToolNames.NEW_CONCEPTUAL_MODEL)
        append(" selected is the tab that **stays** focused — use created URIs for tools on the new empty tab). ")
        append("For ")
        append(McpTabToolNames.OPEN_XML)
        append(" / ")
        append(McpTabToolNames.OPEN_FILE)
        append(", selected is the focused tab after the call.\n\n")

        append("### User-visible UI (tabs + selection)\n")
        append("Tools that change which window is in front or what is selected on the canvas are for **human-in-the-loop** moments only: use ")
        append(McpTabToolNames.FOCUS_WINDOW)
        append(", optional `requestWindowFocus` on ")
        append(McpTabToolNames.SELECT)
        append(", and optional `requestWindowFocus` on ")
        append(McpEditToolNames.CANVAS_SELECTION)
        append(" / ")
        append(McpEditToolNames.CANVAS_SELECTION_RECTANGLE)
        append(" when you genuinely want to **show** the user something or **draw attention** to the brModelo window. ")
        append("Do **not** use window-focus flags for routine headless automation — raising the editor interrupts the user's workflow. ")
        append("After MCP changes selection and/or raises the window, the desktop app shows a short snackbar (Portuguese) so the user knows an agent action occurred.\n\n")

        append("### Static references (always listed while the server runs)\n\n")
        append("DTD (informative for agents; the editor does **not** validate loads against it):\n- ")
        append(conceptualMerDtdResourceUri())
        append("\n\nFrozen example MER XML (copies of desktop test fixtures; read-only, **not** tabs):\n")
        for (ex in mcpClasspathXmlExamples) {
            append("- ")
            append(ex.instructionsSummaryLine)
            append("\n  ")
            append(ex.resourceUri)
            append('\n')
        }
        append("\nWhen authoring new XML for ")
        append(McpTabToolNames.OPEN_XML)
        append(", start from the DTD plus one of the examples above ")
        append("(via resources/read), then adapt — do not rely on random files from the user's disk.\n")

        append("\n### XML editing on open tabs (each call = one undo step)\n")
        append("- ")
        append(McpTabToolNames.REPLACE_MODEL_XML)
        append(": replace the whole conceptual MER XML of a tab (UTF-8). Provide `resourceUri` (any live tab URI) from ")
        append(McpTabToolNames.LIST_OPEN)
        append(".\n- ")
        append(McpTabToolNames.PATCH_MODEL_XML)
        append(": search/replace on the tab's serialized MER XML, then re-parse; set replace_all true only when you intend to change every occurrence of old_string. ")
        append("On success, both XML tab tools attach a `layoutQuality` object (full-diagram overlap, tight-clearance, approximate link-crossing hints, plus `hasBlockingOverlap` / `affectedElementIds` / `agentHint`) so agents can adjust layout; call ")
        append(McpOperationToolNames.LAYOUT_QUALITY)
        append(" anytime for the same analysis with an optional `elementIds` scope.\n")

        append("\n### Resource text utilities (")
        append(McpResourceUtilityToolNames.RESOURCE_UTILITY_GROUP)
        append(McpResourceUtilityToolNames.RESOURCE_UTILITY_SEPARATOR)
        append("… tools)\n")
        append("These tools read or search the **plain text** of registered resource URIs where `resources/read` would return text (same bodies as resources/read for those URIs). ")
        append("Read tools ")
        append(McpResourceUtilityToolNames.READ_FULL)
        append(", ")
        append(McpResourceUtilityToolNames.READ_LINES)
        append(", and ")
        append(McpResourceUtilityToolNames.READ_RANGE)
        append(" return **plain text** on success: the first line is exactly `OK:`, and from the second line onward is the **raw** UTF-16 slice (not JSON). ")
        append(McpResourceUtilityToolNames.READ_FULL)
        append(" returns the full body; ")
        append(McpResourceUtilityToolNames.READ_LINES)
        append(" uses a 1-based inclusive line range; ")
        append(McpResourceUtilityToolNames.READ_RANGE)
        append(" uses a 0-based Kotlin substring range (end index exclusive). ")
        append("Search tools ")
        append(McpResourceUtilityToolNames.SEARCH)
        append(" (literal) and ")
        append(McpResourceUtilityToolNames.SEARCH_REGEX)
        append(" return JSON with character indices and 1-based line/column for each match.\n")

        append("\n### Raster export (")
        append(McpExportToolNames.EXPORT_GROUP)
        append(McpExportToolNames.EXPORT_SEPARATOR)
        append("…)\n")
        append("- ")
        append(McpExportToolNames.SUBSET_RASTER)
        append(": render a tight-cropped PNG or JPEG for an explicit list of canvas `elementIds` on a tab (`resourceUri` from ")
        append(McpTabToolNames.LIST_OPEN)
        append(", any `.xml`/`.png`/`.jpg` suffix for that tab). ")
        append("Attribute trees on selected holders are expanded automatically like Ctrl+C; connections appear when both endpoints are in the expanded id set. ")
        append("`png` matches the transparent clipboard preview; `jpg`/`jpeg` matches the opaque gray background used by **Exportar em JPEG**.\n")
        append("- ")
        append(McpExportToolNames.CURRENT_CANVAS_SELECTION)
        append(": read the user's **live** canvas selection on a tab as JSON (`selectionKind`, `elementIds`, `cardinalityConnectionIds`, `selectedPickCount`, `rasterSeedElementIds`). ")
        append("Omit `imageFormat` for data-only; set `imageFormat` to `png`, `jpg`, or `jpeg` to also return MCP image content (base64) for the same subgraph as Ctrl+C / ")
        append(McpExportToolNames.SUBSET_RASTER)
        append(".\n")
        append("- ")
        append(McpExportToolNames.CANVAS_ELEMENTS_DETAIL)
        append(": resolve **one or more** canvas `elementIds` on a tab to structured JSON (entity/relationship/attribute/… summaries, same field shape as procedural placement responses) plus optional `incidentConnections` touching those ids. ")
        append("Omit `imageFormat` for data-only; set `imageFormat` to `png`, `jpg`, or `jpeg` to also return MCP image content (base64) for the Ctrl+C-expanded subgraph (attribute trees on included holders), matching ")
        append(McpExportToolNames.SUBSET_RASTER)
        append(".\n")

        append("\n### Operations menu (")
        append(McpOperationToolNames.OPERATION_GROUP)
        append(McpOperationToolNames.OPERATION_SEPARATOR)
        append("…)\n")
        append("- ")
        append(McpOperationToolNames.ORGANIZE_ATTRIBUTES)
        append(": same layout rules as **Operações → Organizar Atributos** on the tab's current canvas selection (multi-select aware). ")
        append("Optional `sides` lists only the owner edges to lay out (`left`, `top`, `right`, `bottom`); omit `sides` or pass `[]` for all sides like the menu. ")
        append("One undo step; pass `resourceUri` from ")
        append(McpTabToolNames.LIST_OPEN)
        append(".\n- ")
        append(McpOperationToolNames.MOVE_CANVAS_ELEMENTS)
        append(": translate canvas elements by `deltaX`/`deltaY` in schema pixels with the same cardinality fixed/floating behaviour as dragging; optional `moveOwnedCanvasAttributes` (default true) moves on-canvas attributes whose owner is among the moved elements. Returns `layoutQuality` scoped to the moved ids (check `hasBlockingOverlap` / `agentHint` after moves). One undo step.\n- ")
        append(McpOperationToolNames.LAYOUT_QUALITY)
        append(": overlap / tight-gap / approximate connection-crossing diagnostics for a tab (`resourceUri` from ")
        append(McpTabToolNames.LIST_OPEN)
        append("). ")
        append("Optional `elementIds` limits reported issues to anything touching those canvas element ids; omit `elementIds` or pass `[]` for a full-tab scan. ")
        append("Many procedural and inspector-edit tools also merge a `layoutQuality` field into their success JSON when layout may have changed (scoped to touched ids where practical); prefer PNG/JPEG tab resources or subset raster export to confirm real line routing. Newer responses include `hasBlockingOverlap`, `affectedElementIds`, and optional `agentHint` inside `layoutQuality`.\n")

        append("\n### Procedural canvas tools (")
        append(McpProceduralToolsToolNames.TOOLS_GROUP)
        append(McpProceduralToolsToolNames.TOOLS_SEPARATOR)
        append("…)\n")
        append("Place entities, relationships, associative entities, and observation boxes step-by-step with the same domain rules as the ribbon tools, ")
        append("without changing the user's currently selected canvas tool: ")
        append(McpProceduralToolsToolNames.PLACE_ENTITY)
        append(", ")
        append(McpProceduralToolsToolNames.PLACE_RELATIONSHIP)
        append(", ")
        append(McpProceduralToolsToolNames.PLACE_ASSOCIATIVE_ENTITY)
        append(". ")
        append("Place an observation / annotation text box like the ribbon **Observação** tool: ")
        append(McpProceduralToolsToolNames.PLACE_OBSERVATION)
        append(" (optional caption, notes, dictionary, font style, box colour, annotation type 0–2, text alignment 0–2, autoSize, width/height). ")
        append("Apply specialization on an existing entity id (baseEntityId; pass `resourceUri` from ")
        append(McpTabToolNames.LIST_OPEN)
        append("): ")
        append(McpProceduralToolsToolNames.APPLY_SPECIALIZATION_BASIC)
        append(" (triangle only), ")
        append(McpProceduralToolsToolNames.APPLY_SPECIALIZATION_TREE)
        append(" (small tree: specialization + child entity; set boolean `exclusive`: true = restricted, false = optional). ")
        append("Link two diagram endpoints: **full editor** behaviour (entity↔entity with automatic relationship creation, entity↔associative outer bridge, specialization↔plain entity, etc.) via ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append("; or **existing-endpoint wiring** (rejects plain entity–entity auto-diamond; may rewrite entity+associative-outer to inner) via ")
        append(McpProceduralToolsToolNames.LINK_EXISTING_ENDPOINTS)
        append(" — same JSON schema and `dryRun` preview; responses share the same rich success shape (see each tool description), including `linkPattern` when the domain classifies the outcome. ")
        append("Create an **Auto Relacionar** self-relationship on one entity id with optional `attachSide` (same strings as attribute tools) and the same override knobs for the diamond plus two cardinality legs: ")
        append(McpProceduralToolsToolNames.AUTO_SELF_RELATIONSHIP)
        append(". ")
        append("Each placement or specialization call returns JSON for the new primary element (id, bounds, names, style); ")
        append(McpProceduralToolsToolNames.LINK_OBJECTS)
        append(" / ")
        append(McpProceduralToolsToolNames.LINK_EXISTING_ENDPOINTS)
        append(" return a richer JSON body (see tool descriptions).\n")

        append("\n### Conceptual attributes (")
        append(McpAttributeToolsToolNames.ATTRIBUTE_TOOLS_GROUP)
        append(McpAttributeToolsToolNames.ATTRIBUTE_TOOLS_SEPARATOR)
        append("…)\n")
        append("Add canvas attributes like the attribute ribbon tool (without switching the active tool): ")
        append(McpAttributeToolsToolNames.APPLY_ATTRIBUTE)
        append(" (`attributeVariant`: basic, identifier, multivalued, optional; optional `attachSide` left/top/right/bottom; optional `overrides`). ")
        append("Placement hints for agents (heuristics, not enforced limits): keep attributes for the same owner on the **same side** when possible — **prefer the right** side for consistency; ")
        append("when `attachSide` is omitted the editor picks the least crowded side with a **right-side tie-break**. ")
        append("If a chosen side would **cover** important entities or relationships on the diagram, pick another `attachSide` so labels stay readable. ")
        append("At default entity size (~102×66 px) and default attribute boxes (~73×16), about **five** attributes per **left/right** edge usually stay legible; ")
        append("about **twenty-four** stacked along **top/bottom** still feels comfortable — beyond that layouts tend to feel tight. ")
        append("Create a composite with explicit leaf `children` (no nested composite in one call; optional `nestedHiddenAttributes` on the new parent): ")
        append(McpAttributeToolsToolNames.APPLY_COMPOSITE_ATTRIBUTE)
        append(". ")
        append("Append full recursive hidden-attribute trees to any holder that supports ocultos in the inspector: ")
        append(McpAttributeToolsToolNames.APPLY_HIDDEN_ATTRIBUTE)
        append(" (`roots` array). Simple/composite responses include `element` JSON; hidden append returns `holderElementId` and `appendedRootCount`.\n")

        append("\n### Property edit tools (")
        append(McpEditToolNames.EDIT_GROUP)
        append(McpEditToolNames.EDIT_SEPARATOR)
        append("…)\n")
        append("Each successful edit call is **one undo step**, like changing a field in the inspector — except ")
        append(McpEditToolNames.CANVAS_SELECTION)
        append(" and ")
        append(McpEditToolNames.CANVAS_SELECTION_RECTANGLE)
        append(", which only update the live canvas selection (no schema mutation, no undo entry). ")
        append("Pass `resourceUri` (`brmodelo://model/{editorTabSessionId}.xml|.png|.jpg` from ")
        append(McpTabToolNames.LIST_OPEN)
        append("). ")
        append("Patches use strict JSON schemas (`additionalProperties: false`); the runtime also rejects keys that do not apply to the target (English error codes such as `field_not_applicable_to_element_kind`).\n")
        append("- ")
        append(McpEditToolNames.MODEL)
        append(": patch `name`, `author`, and/or `observations` (same as the empty-canvas inspector block; `version` is read-only and cannot be patched).\n")
        append("- ")
        append(McpEditToolNames.CANVAS_ELEMENT)
        append(": patch a canvas `elementId` (names, dictionary, observations, `position`, label style, type-specific fields such as arrow direction, attribute flags, annotation appearance, etc.). ")
        append("Attribute edits run the same auto-size and composite bar relayout pass as the UI when relevant.\n")
        append("- ")
        append(McpEditToolNames.CONNECTION)
        append(": patch a `connectionId` row (cardinality code, visibility, orientation, weak link, role text, observations, dictionary, label box position/size, associative outer flags, fixed vs floating label, auto-size). ")
        append("Toggling fixed position, cardinality auto-size, or showing the label may materialize default bounds like the inspector.\n")
        append("- ")
        append(McpEditToolNames.HIDDEN_ATTRIBUTE)
        append(": patch one oculto node via `holderElementId` and a `path` of merged child indices (canvas children first, then nested ocultos at each level, same order as the inspector tree). ")
        append("Names must stay unique and non-blank across siblings after the edit.\n")
        append("- ")
        append(McpEditToolNames.CANVAS_SELECTION)
        append(": set the user's canvas selection from `elementIds` and/or `cardinalityConnectionIds` (same multi-pick shape as Shift/rectangle selection; omit or use [] to clear a side). ")
        append("Validates ids against the tab schema; optional `requestWindowFocus` raises the editor window — use sparingly (see **User-visible UI** above).\n")
        append("- ")
        append(McpEditToolNames.CANVAS_SELECTION_RECTANGLE)
        append(": marquee in schema coordinates (`x0`,`y0`,`x1`,`y1`) with `mergeMode` add | replace | subtract (same geometric hits as the rectangle tool); optional `dryRun` previews `objectsInBand`, `selectionUiAfter`, and `selectionSymmetricDelta` without changing the UI (focus flags ignored). ")
        append("Optional `requestWindowFocus` when applying raises the window — use sparingly.\n")

        append("\n### Conceptual search (")
        append(McpSearchToolNames.SEARCH_GROUP)
        append(McpSearchToolNames.SEARCH_SEPARATOR)
        append("…)\n")
        append("Find in-memory diagram text with the same rules as **Localizar** (accent-insensitive substring, optional type filters, dictionary/observations flags, 400-hit cap): ")
        append(McpSearchToolNames.FIND)
        append(". Blank `query` lists every candidate in the selected type flags (same 400-hit cap; `matchedIn` may be empty). ")
        append("Apply one hit to focus the editor (selection, inspector tab, hidden-attribute path, canvas pan): ")
        append(McpSearchToolNames.APPLY_HIT)
        append(". Pass the `hit` object echoed from a prior find call; include `resourceUri` (`.xml`, `.png`, or `.jpg` from ")
        append(McpTabToolNames.LIST_OPEN)
        append(").\n")
    }
}
