/*
 * Power brModelo - Kotlin port of brModelo 3.0 originally written in Pascal
 * Copyright (C) 2026  Polyana Fontes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package games.polyclub.power.brmodelo.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Colours for application chrome: ribbon, main menu, dialogs, inspector, outer window surface,
 * Chromium-style tabs where they are **not** diagram-specific, and status-adjacent panels.
 *
 * Provide [LocalAppColorPalette] once near the root of the app (see [games.polyclub.power.brmodelo.App]).
 */
data class AppColorPalette(
    val windowSurface: Color,
    val ribbonBackground: Color,
    val ribbonGroupBackground: Color,
    val ribbonBorder: Color,
    val ribbonSeparator: Color,
    val ribbonGroupTitle: Color,
    val ribbonTabInactive: Color,
    val ribbonHoverBackground: Color,
    val ribbonHoverBorder: Color,
    val ribbonSplitDividerActive: Color,
    val ribbonSplitMainSegmentHover: Color,
    val ribbonToolArmedIdleFill: Color,
    val ribbonToolArmedBorder: Color,
    val ribbonSplitArrowSegmentHover: Color,
    val ribbonDropdownIconStripe: Color,
    val ribbonDropdownHover: Color,
    val ribbonHamburgerBackground: Color,
    val ribbonHamburgerBar: Color,
    val mainMenuBackground: Color,
    val mainMenuActive: Color,
    val mainMenuBorder: Color,
    val mainMenuSubmenuBackground: Color,
    val mainMenuText: Color,
    val mainMenuSeparator: Color,
    val mainMenuItemDisabledBackground: Color,
    val mainMenuItemDisabledText: Color,
    val mainMenuSubmenuChevron: Color,
    val mainMenuSectionTitle: Color,
    val mainMenuMutedItalic: Color,
    val mainMenuModelPickerRowIdle: Color,
    val mainMenuModelPickerRowHovered: Color,
    val mainMenuModelPickerRowDisabled: Color,
    val mainMenuModelPickerBorder: Color,
    val mainMenuModelPickerSecondary: Color,
    val mainMenuModelPickerSecondaryDisabled: Color,
    val canvasTabStripBackground: Color,
    val canvasTabActiveBackground: Color,
    val canvasTabInactiveBackground: Color,
    val canvasTabStripBorder: Color,
    val canvasPanelBorderIdle: Color,
    val inspectorBackground: Color,
    val inspectorBorder: Color,
    val inspectorHeaderBackground: Color,
    val inspectorTabActiveBackground: Color,
    val inspectorTabInactiveBackground: Color,
    val inspectorTabStripBorder: Color,
    val inspectorSectionHeaderBackground: Color,
    val inspectorCellLabelBackground: Color,
    val inspectorCellLabelFocusedBackground: Color,
    val inspectorCellValueBackground: Color,
    val inspectorCellValueReadOnlyBackground: Color,
    val inspectorCellBorder: Color,
    val inspectorLabelText: Color,
    val inspectorLabelFocusedText: Color,
    val inspectorValueText: Color,
    val inspectorHintBackground: Color,
    val inspectorHintText: Color,
    val inspectorBulkDeleteWarning: Color,
    val inspectorSchemaHeaderTitle: Color,
    val inspectorSectionDivider: Color,
    val inspectorMultilineTitle: Color,
    val inspectorValueBorderFocused: Color,
    val inspectorValueBorderDisabled: Color,
    val inspectorValueBorderReadOnly: Color,
    val inspectorSearchPlaceholder: Color,
    val inspectorTreeRowSelectedBackground: Color,
    val inspectorTreeBullet: Color,
    val inspectorTreePrimaryText: Color,
    val inspectorTooltipBackground: Color,
    val inspectorTooltipBorder: Color,
    val inspectorTooltipText: Color,
    val fontDialogSectionHeaderBackground: Color,
    val fontDialogCellBorder: Color,
    val fontDialogCellLabelBackground: Color,
    val fontDialogCellValueBackground: Color,
    val fontDialogLabelText: Color,
    val fontDialogValueText: Color,
    val fontDialogSurface: Color,
    val fontDialogListSelectionBackground: Color,
    val fontDialogListSelectionForeground: Color,
    val fontDialogTitleText: Color,
    val fontDialogLabelPreviewBase: Color,
    val hiddenAttributeEditorMutedNote: Color,
    val ribbonDropdownSurface: Color,
    val ribbonDropdownDivider: Color,
    val ribbonDropdownItemText: Color,
    val ribbonDropdownItemTextDisabled: Color,
    val chromiumTabSelectedText: Color,
    val chromiumTabUnselectedText: Color,
    val chromiumTabCloseHoverScrim: Color,
    val ribbonControlPrimaryText: Color,
    val ribbonControlPrimaryTextDisabled: Color,
    val ribbonControlChevron: Color,
    val ribbonControlChevronDisabled: Color,
    val ribbonSplitArrow: Color,
    val ribbonSplitArrowDisabled: Color,
    val ribbonIaIconInk: Color,
    val ribbonIaIconAccent: Color,
    val ribbonIaIconMuted: Color,
    val ribbonIaRecordFill: Color,
) {
    companion object {
        /** Default light palette matching the previous hard-coded values. */
        fun light(): AppColorPalette = AppColorPalette(
            windowSurface = Color(0xFFE3E3E3),
            ribbonBackground = Color(0xFFDDE4EE),
            ribbonGroupBackground = Color(0xFFEBF0F8),
            ribbonBorder = Color(0xFF9AAABB),
            ribbonSeparator = Color(0xFFBBCCDD),
            ribbonGroupTitle = Color(0xFF7A8FA0),
            ribbonTabInactive = Color(0xFFC4CFDB),
            ribbonHoverBackground = Color(0xFFFFF3C0),
            ribbonHoverBorder = Color(0xFFE8A800),
            ribbonSplitDividerActive = Color(0xFFE8C040),
            ribbonSplitMainSegmentHover = Color(0xFFFFE078),
            ribbonToolArmedIdleFill = Color(0xFFFFF6D8),
            ribbonToolArmedBorder = Color(0xFFC9A94A),
            ribbonSplitArrowSegmentHover = Color(0xFFF0C85A),
            ribbonDropdownIconStripe = Color(0xFFF3F7FB),
            ribbonDropdownHover = Color(0xFFCCDDEE),
            ribbonHamburgerBackground = Color(0xFF3E5A7E),
            ribbonHamburgerBar = Color.White,
            mainMenuBackground = Color(0xFFEEF2F8),
            mainMenuActive = Color(0xFFFFBF00),
            mainMenuBorder = Color(0xFFA0AEBC),
            mainMenuSubmenuBackground = Color(0xFFF8F9FC),
            mainMenuText = Color(0xFF1C2B3A),
            mainMenuSeparator = Color(0xFFC0CAD4),
            mainMenuItemDisabledBackground = Color(0xFFE8EBF0),
            mainMenuItemDisabledText = Color(0xFF8899AA),
            mainMenuSubmenuChevron = Color(0xFF667788),
            mainMenuSectionTitle = Color(0xFF253041),
            mainMenuMutedItalic = Color(0xFF888888),
            mainMenuModelPickerRowIdle = Color(0xFFF0F4FA),
            mainMenuModelPickerRowHovered = Color(0xFFDDE6F4),
            mainMenuModelPickerRowDisabled = Color(0xFFE5E8ED),
            mainMenuModelPickerBorder = Color(0xFFCDD6E2),
            mainMenuModelPickerSecondary = Color(0xFF4D5C6A),
            mainMenuModelPickerSecondaryDisabled = Color(0xFF9AA5AE),
            canvasTabStripBackground = Color(0xFFD7D7D7),
            canvasTabActiveBackground = Color(0xFFEEEEEE),
            canvasTabInactiveBackground = Color(0xFFC8C8C8),
            canvasTabStripBorder = Color(0xFF888888),
            canvasPanelBorderIdle = Color(0xFF7A7A7A),
            inspectorBackground = Color(0xFFF0F2F5),
            inspectorBorder = Color(0xFF8090A0),
            inspectorHeaderBackground = Color(0xFFD8D8D8),
            inspectorTabActiveBackground = Color(0xFFFFFFFF),
            inspectorTabInactiveBackground = Color(0xFFBBBBBB),
            inspectorTabStripBorder = Color(0xFF8C8C8C),
            inspectorSectionHeaderBackground = Color(0xFFD2D5D8),
            inspectorCellLabelBackground = Color(0xFFDFE2E6),
            inspectorCellLabelFocusedBackground = Color(0xFF4A5868),
            inspectorCellValueBackground = Color(0xFFFFFFFF),
            inspectorCellValueReadOnlyBackground = Color(0xFFECEEF1),
            inspectorCellBorder = Color(0xFFB8BCC0),
            inspectorLabelText = Color(0xFF2A3A4A),
            inspectorLabelFocusedText = Color(0xFFFFFFFF),
            inspectorValueText = Color(0xFF1A2535),
            inspectorHintBackground = Color(0xFFDCDFE2),
            inspectorHintText = Color(0xFF2A3040),
            inspectorBulkDeleteWarning = Color(0xFFB00020),
            inspectorSchemaHeaderTitle = Color(0xFF606070),
            inspectorSectionDivider = Color(0xFF7A9ABF),
            inspectorMultilineTitle = Color(0xFF1C2D3E),
            inspectorValueBorderFocused = Color(0xFF80A0C0),
            inspectorValueBorderDisabled = Color(0xFF9AA0A8),
            inspectorValueBorderReadOnly = Color(0xFF80A0C0),
            inspectorSearchPlaceholder = Color(0xFF7A8A9A),
            inspectorTreeRowSelectedBackground = Color(0xFFC8DCFA),
            inspectorTreeBullet = Color(0xFF5080B0),
            inspectorTreePrimaryText = Color(0xFF1A2535),
            inspectorTooltipBackground = Color(0xFFDCE6F0),
            inspectorTooltipBorder = Color(0xFF8090A8),
            inspectorTooltipText = Color(0xFF1A2535),
            fontDialogSectionHeaderBackground = Color(0xFFD2D5D8),
            fontDialogCellBorder = Color(0xFFB8BCC0),
            fontDialogCellLabelBackground = Color(0xFFDFE2E6),
            fontDialogCellValueBackground = Color(0xFFFFFFFF),
            fontDialogLabelText = Color(0xFF2A3A4A),
            fontDialogValueText = Color(0xFF1A2535),
            fontDialogSurface = Color(0xFFF0F2F5),
            fontDialogListSelectionBackground = Color(0xFF0078D7),
            fontDialogListSelectionForeground = Color.White,
            fontDialogTitleText = Color(0xFF1C2D3E),
            fontDialogLabelPreviewBase = Color.Black,
            hiddenAttributeEditorMutedNote = Color(0xFF7A8A9A),
            ribbonDropdownSurface = Color.White,
            ribbonDropdownDivider = Color(0xFFDDE4EE),
            ribbonDropdownItemText = Color(0xFF1C2B3A),
            ribbonDropdownItemTextDisabled = Color(0xFFAAAAAA),
            chromiumTabSelectedText = Color(0xFF1B2B3B),
            chromiumTabUnselectedText = Color(0xFF55667A),
            chromiumTabCloseHoverScrim = Color(0x30000000),
            ribbonControlPrimaryText = Color(0xFF2C3E50),
            ribbonControlPrimaryTextDisabled = Color(0xFF8A8A8A),
            ribbonControlChevron = Color(0xFF556677),
            ribbonControlChevronDisabled = Color(0xFFAAAAAA),
            ribbonSplitArrow = Color(0xFF556677),
            ribbonSplitArrowDisabled = Color(0xFFAAAAAA),
            ribbonIaIconInk = Color(0xFF2C3E50),
            ribbonIaIconAccent = Color(0xFF3498DB),
            ribbonIaIconMuted = Color(0xFF95A5A6),
            ribbonIaRecordFill = Color(0xFFC0392B),
        )
    }
}

val LocalAppColorPalette = staticCompositionLocalOf { AppColorPalette.light() }
